# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-09-16 14:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Name')),
                ('logo', models.ImageField(upload_to=utils.rename_image)),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrption')),
                ('information', models.TextField(blank=True, null=True, verbose_name='Info')),
                ('url', models.SlugField(max_length=164)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('maintainers', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Maintainers')),
            ],
        ),
    ]
