# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-09-16 18:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': 'Project', 'verbose_name_plural': 'Projects'},
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(default='Teste', max_length=100, unique=True, verbose_name='Name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='url',
            field=models.SlugField(max_length=164, verbose_name='url'),
        ),
    ]
